## 練習時間
假設我們資料中類別的數量並不均衡，在評估準確率時可能會有所偏頗，試著切分出 y_test 中，0 類別與 1 類別的數量是一樣的 (亦即 y_test 的類別是均衡的)

In [1]:
import numpy as np
X = np.arange(1000).reshape(200, 5)
y = np.zeros(200)
y[:40] = 1

In [2]:
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

可以看見 y 類別中，有 160 個 類別 0，40 個 類別 1 ，請試著使用 train_test_split 函數，切分出 y_test 中能各有 10 筆類別 0 與 10 筆類別 1 。(HINT: 參考函數中的 test_size，可針對不同類別各自作切分後再合併)

In [7]:
from sklearn.model_selection import train_test_split, KFold
X_train1, X_test1, y_train1, y_test1 = train_test_split(X[:40], y[:40], test_size=0.25, stratify=y[:40])

In [11]:
X_train1

array([[ 50,  51,  52,  53,  54],
       [190, 191, 192, 193, 194],
       [180, 181, 182, 183, 184],
       [140, 141, 142, 143, 144],
       [115, 116, 117, 118, 119],
       [125, 126, 127, 128, 129],
       [135, 136, 137, 138, 139],
       [145, 146, 147, 148, 149],
       [  0,   1,   2,   3,   4],
       [155, 156, 157, 158, 159],
       [105, 106, 107, 108, 109],
       [170, 171, 172, 173, 174],
       [ 70,  71,  72,  73,  74],
       [ 60,  61,  62,  63,  64],
       [110, 111, 112, 113, 114],
       [160, 161, 162, 163, 164],
       [ 25,  26,  27,  28,  29],
       [175, 176, 177, 178, 179],
       [ 35,  36,  37,  38,  39],
       [ 85,  86,  87,  88,  89],
       [ 20,  21,  22,  23,  24],
       [120, 121, 122, 123, 124],
       [185, 186, 187, 188, 189],
       [ 30,  31,  32,  33,  34],
       [ 75,  76,  77,  78,  79],
       [  5,   6,   7,   8,   9],
       [ 40,  41,  42,  43,  44],
       [ 80,  81,  82,  83,  84],
       [165, 166, 167, 168, 169],
       [ 90,  

In [12]:
y_test1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
X_train0, X_test0, y_train0, y_test0 = train_test_split(X[40:], y[40:], test_size=0.0625, stratify=y[40:])

In [14]:
y_test0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
x_train, y_train = np.concatenate([X_train0, X_train1]), np.concatenate([y_train0, y_train1])
x_test, y_test = np.concatenate([X_test0, X_test1]), np.concatenate([y_test0, y_test1])
y_test

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])